name: Release Go Application

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Install dependencies
        run: go mod download
      - name: Build and package Linux binary
        run: |
          mkdir -p build/linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X 'csv-tools/cmd.Version=${{github.ref_name}}'" -o build/linux/csv-tools
          cd build/linux
          zip ../csv-tools:${{github.ref_name}}-linux-amd64.zip csv-tools
          cd ../..
      - name: Build and package Windows binary
        run: |
          mkdir -p build/windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X 'csv-tools/cmd.Version=${{github.ref_name}}'" -o build/windows/csv-tools.exe
          cd build/windows
          zip ../csv-tools:${{github.ref_name}}-windows-amd64.zip csv-tools.exe
          cd ../..
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/csv-tools:${{github.ref_name}}-linux-amd64.zip
            build/csv-tools:${{github.ref_name}}-windows-amd64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
